### ISSUE TITLE
"RuntimeError: OrderedDict mutated during iteration" on specific valid rss feed

### ISSUE THREAD

**Issue by hpr** [wking/rss2email#109]
r2e add testfeed https://habs.sdf.org/feeds/testfeed.rss
    r2e run testfeed --no-send
    Traceback (most recent call last):
      File "/meta/h/habs/.local/bin/r2e", line 5, in <module>
        rss2email.main.run()
      File "/meta/h/habs/.local/lib/python3.6/site-packages/rss2email/main.py", line 163, in run
        args.func(feeds=feeds, args=args)
      File "/meta/h/habs/.local/lib/python3.6/site-packages/rss2email/command.py", line 62, in run
        feed.run(send=args.send)
      File "/meta/h/habs/.local/lib/python3.6/site-packages/rss2email/feed.py", line 838, in run
        for (guid, id_, sender, message) in self._process(parsed):
      File "/meta/h/habs/.local/lib/python3.6/site-packages/rss2email/feed.py", line 357, in _process
        processed = self._process_entry(parsed=parsed, entry=entry)
      File "/meta/h/habs/.local/lib/python3.6/site-packages/rss2email/feed.py", line 470, in _process_entry
        for k,v in extra_headers.items():  # remove empty tags, etc.
    RuntimeError: OrderedDict mutated during iteration

It's a valid RSS feed: https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fhabs.sdf.org%2Ffeeds%2Ftestfeed.rss

r2e works fine for other feeds I use, just not this one and I'm not sure why. Using r2e v3.9.

**Comment by gkleen** [comment]
This was fixed in 60870d9ff. Time for a new release @wking?

**Comment by Ekleog** [comment]
Hello,

This repository has been deprecated for a few years now, and has been replaced by https://github.com/rss2email/rss2email .

If this issue is still relevant to you, and not fixed with v3.12.2, could you please reopen the issue there?

Cheers,
  Leo
