### ISSUE TITLE
AttributeError: module 'html2text' has no attribute 'unescape'

### ISSUE THREAD

**Issue by l29ah** [wking/rss2email#116]
```
Traceback (most recent call last):
  File "/home/l29ah/rss2email/rss2email/r2e", line 5, in <module>
    rss2email.main.run()
  File "/home/l29ah/rss2email/rss2email/rss2email/main.py", line 163, in run
    args.func(feeds=feeds, args=args)
  File "/home/l29ah/rss2email/rss2email/rss2email/command.py", line 62, in run
    feed.run(send=args.send)
  File "/home/l29ah/rss2email/rss2email/rss2email/feed.py", line 842, in run
    for (guid, id_, sender, message) in self._process(parsed):
  File "/home/l29ah/rss2email/rss2email/rss2email/feed.py", line 357, in _process
    processed = self._process_entry(parsed=parsed, entry=entry)
  File "/home/l29ah/rss2email/rss2email/rss2email/feed.py", line 462, in _process_entry
    sender = self._get_entry_email(parsed=parsed, entry=entry)
  File "/home/l29ah/rss2email/rss2email/rss2email/feed.py", line 652, in _get_entry_email
    name = self._get_entry_name(parsed=parsed, entry=entry)
  File "/home/l29ah/rss2email/rss2email/rss2email/feed.py", line 602, in _get_entry_name
    return _html2text.unescape(name)
AttributeError: module 'html2text' has no attribute 'unescape'
```

**Comment by l29ah** [comment]
https://github.com/rss2email/rss2email/commit/81824e25723dcd2936f25f64ebc16f2e8ec9f310

**Comment by Ekleog** [comment]
Hello,

This repository has been deprecated for a few years now, and has been replaced by https://github.com/rss2email/rss2email .

If this issue is still relevant to you, and not fixed with v3.12.2, could you please reopen the issue there?

Cheers,
  Leo
