### ISSUE TITLE
email.errors.HeaderParseError: header value appears to contain an embedded header

### ISSUE THREAD

**Issue by craigmaloney** [wking/rss2email#84]
Getting the following error on this feed:

http://sarahcandersen.com/rss

Traceback (most recent call last):
  File "bin/r2e", line 5, in <module>
    rss2email.main.run()
  File "/home/craig/.virtualenvs/rss2email3/lib/python3.4/site-packages/rss2email/main.py", line 163, in run
    args.func(feeds=feeds, args=args)
  File "/home/craig/.virtualenvs/rss2email3/lib/python3.4/site-packages/rss2email/command.py", line 62, in run
    feed.run(send=args.send)
  File "/home/craig/.virtualenvs/rss2email3/lib/python3.4/site-packages/rss2email/feed.py", line 842, in run
    for (guid, id_, sender, message) in self._process(parsed):
  File "/home/craig/.virtualenvs/rss2email3/lib/python3.4/site-packages/rss2email/feed.py", line 357, in _process
    processed = self._process_entry(parsed=parsed, entry=entry)
  File "/home/craig/.virtualenvs/rss2email3/lib/python3.4/site-packages/rss2email/feed.py", line 502, in _process_entry
    section=self.section)
  File "/home/craig/.virtualenvs/rss2email3/lib/python3.4/site-packages/rss2email/email.py", line 119, in get_message
    sender_name = str(_Header(sender_name, sender_encoding).encode())
  File "/usr/lib/python3.4/email/header.py", line 393, in encode
    "an embedded header: {!r}".format(value))
email.errors.HeaderParseError: header value appears to contain an embedded header: "Sarah's\nScribbles: <author>"

**Comment by Ekleog** [comment]
Hello,

This repository has been deprecated for a few years now, and has been replaced by https://github.com/rss2email/rss2email .

If this issue is still relevant to you, and not fixed with v3.12.2, could you please reopen the issue there?

Cheers,
  Leo
